kafka:
  consumer:
    kafkaServer: localhost:9092
  backoff:
    interval: 200
    maxAttempts: 4
spring:
  artemis:
    mode: native
    broker-url: "tcp://localhost:61616"
    user: ${ARTEMIS_USER}
    password: ${ARTEMIS_PASSWORD}
  jms:
    cache:
      session-cache-size: 5